In [2]:
import pandas as pd

In [3]:
cd = pd.read_csv("olist_customers_dataset.csv") 
gd=pd.read_csv("olist_geolocation_dataset.csv")
ot=pd.read_csv("olist_order_items_dataset.csv")
od=pd.read_csv("olist_orders_dataset.csv")
pyd=pd.read_csv("olist_order_payments_dataset.csv")
ord=pd.read_csv("olist_order_reviews_dataset.csv")
odd=pd.read_csv("olist_orders_dataset.csv")
prd=pd.read_csv("olist_products_dataset.csv")
osd=pd.read_csv("olist_sellers_dataset.csv")
pcn=pd.read_csv("product_category_name_translation.csv")

📊 Business Request: Understand Customer Spending Behavior

                            customer_id  customer_spend
8475   1617b1357756262bfa56ab541c47bc16         13440.0
91284  ec5b2ba62e574342386871631fafd3fc          7160.0
76948  c6e2731c5b391845f6800c97401a43a9          6735.0
94398  f48d464a0baaea338cb25f816991ab1f          6729.0
24603  3fd6777bbce08a352fddd04e4a7cc8f6          6499.0
2049   05455dfa7cd02f13d132aa7a6a9729c6          5934.6
86248  df55c14d1476a9a3467f131269c2477f          4799.0
14182  24bbf5fd2f2e1b359ee7de94defc4a15          4690.0
86733  e0a2412720e9ea4f26c1ac985f6a7358          4599.9
23771  3d979689f636322c62418b6346b1c6d2          4590.0

In [35]:
# Average order value
order_value=ot.groupby('order_id')['price'].sum().reset_index()
average_order_value=round(order_value['price'].mean(), 2)
print(average_order_value)

137.75

In [17]:
# Typical order value
typical_order_value=order_value['price'].median()
print(typical_order_value)

86.9

In [47]:
customer_spends=od.merge(ot[['order_id','price']],on='order_id').groupby('customer_id')['price'].sum().reset_index(name='customer_spend').sort_values(ascending=False,by='customer_spend').head(10)

In [48]:
customer_spends

                            customer_id  customer_spend
8475   1617b1357756262bfa56ab541c47bc16         13440.0
91284  ec5b2ba62e574342386871631fafd3fc          7160.0
76948  c6e2731c5b391845f6800c97401a43a9          6735.0
94398  f48d464a0baaea338cb25f816991ab1f          6729.0
24603  3fd6777bbce08a352fddd04e4a7cc8f6          6499.0
2049   05455dfa7cd02f13d132aa7a6a9729c6          5934.6
86248  df55c14d1476a9a3467f131269c2477f          4799.0
14182  24bbf5fd2f2e1b359ee7de94defc4a15          4690.0
86733  e0a2412720e9ea4f26c1ac985f6a7358          4599.9
23771  3d979689f636322c62418b6346b1c6d2          4590.0

In [51]:
threshold = customer_spends['customer_spend'].quantile(0.90)

In [55]:
customer_spends[customer_spends['customer_spend'] > threshold]

                           customer_id  customer_spend
8475  1617b1357756262bfa56ab541c47bc16         13440.0

# Is spending consistent?